### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dg0yt** [RealTimeChris/Jsonifier#1]
https://github.com/RealTimeChris/Jsonifier/blob/98c453199ef3dc6aebd90d97e13c53b1cb4a724c/CMakeLists.txt#L29

This variable name is for the user building the project. If you want to give it a default, make it a cache variable.

https://github.com/RealTimeChris/Jsonifier/blob/98c453199ef3dc6aebd90d97e13c53b1cb4a724c/CMakeLists.txt#L47

This variable is undefined. If the desired effect cannot be achieved by inspecting standard variables, it probably should be an option.

https://github.com/RealTimeChris/Jsonifier/blob/98c453199ef3dc6aebd90d97e13c53b1cb4a724c/CMakeLists.txt#L55-L57

This is inconsistent: C++20 or C++23?

https://github.com/RealTimeChris/Jsonifier/blob/98c453199ef3dc6aebd90d97e13c53b1cb4a724c/CMakeLists.txt#L115-L117

The CamelCase `Include` feels strange.
I didn't spot the corresponding install interface. For vcpkg, it would be nice if the lib was designed to install headers to `<vcpkg install dir>/include/jsonifier` IMO.

**Comment by RealTimeChris** [comment]
Alright thanks for the input!
